# Generated by Django 2.2.7 on 2019-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
